[project]
name = "learn-vertex"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-genai>=0.4.0",
    "python-dotenv>=1.0.1",
    "ruff>=0.9.1",
]
